filedir: files

bone:
    plain:    {weight: 20, num_atch:  0, depth: 0 }
    multi1:   {weight: 30, num_atch:  1, depth: 1 }
    multi3:   {weight: 10, num_atch:  3, depth: 1 }
    multi10:  {weight: 20, num_atch: 10, depth: 1 }
    multi3_2: {weight: 10, num_atch:  3, depth: 2 }
    multi3_5: {weight: 10, num_atch:  3, depth: 5 }

base_text:
    base: { weight: 100, file: txt.001K }

attachment:
    txt010Knorm0: { weight: 920, file: txt.010K }
    jpg200Knorm0: { weight:  30, file: jpg.200K.jpg }
    zip100Knorm1: { weight:  25, file: zip.100K.zip }
    tgz005Mnorm2: { weight:   1, file: tgz.005M.tar.gz }
    zip100Knorm5: { weight:  12, file: zip.100K.zip.zip.zip.zip.zip }
    zip100Kviei1: { weight:   1, file: zip.virus.eicar.zip }
    zip100Kvivm1: { weight:   1, file: zip.virus.vmpck.zip }
    zip100Kvibu1: { weight:   1, file: zip.virus.bugbear.zip }
    zip100Kviba1: { weight:   1, file: zip.virus.badtrans.zip }
    tgz010Kviei2: { weight:   1, file: tgz.virus.eicar.tar.gz }
    tgz010Kvivm2: { weight:   1, file: tgz.virus.vmpck.tar.gz }
    tgz010Kvibu2: { weight:   1, file: tgz.virus.bugbear.tar.gz }
    tgz010Kviba2: { weight:   1, file: tgz.virus.badtrans.tar.gz }
    zip010Kviei5: { weight:   1, file: zip.virus.eicar.zip.zip.zip.zip.zip }
    zip010Kvivm5: { weight:   1, file: zip.virus.vmpck.zip.zip.zip.zip.zip }
    zip010Kvibu5: { weight:   1, file: zip.virus.bugbear.zip.zip.zip.zip.zip }
    zip010Kviba5: { weight:   1, file: zip.virus.badtrans.zip.zip.zip.zip.zip }

encode_type:
    base64: { weight: 40, charset: utf-8 }
    qp:     { weight: 40, charset: iso-8859-1 }
    no_enc: { weight: 20, charset: iso-2022-jp }
